apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.22
        env:
        - name: POSTGRES_PASSWORD
          value: "root"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "test"
        ports:
        - containerPort: 3306