apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: qq3
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.22-bookworm
        env:
        - name: POSTGRES_PASSWORD
          value: "test"
        ports:
        - containerPort: 5432