
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-development
  namespace: qq3
  labels:
    app: nginx-development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-development
  template:
    metadata:
      labels:
        app: nginx-development
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
