apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-deployment
  labels:
    app: class
  namespace: mocktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.20
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: class-service
  namespace: mocktest
spec:
  selector:
    app: Class
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443 
  type: NodePort
