apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  namespace: ca2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: class-app-svc
  namespace: ca2
spec:
  selector:
    app: class
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer