apiVersion: v1
kind: Namespace
metadata:
  name: class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-deployment
  namespace: ca2
  labels:
    app: class
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: class-svc
  namespace: class
spec:
  selector:
    app.kubernetes.io/name: class
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer
