apiVersion: v1
kind: Namespace
metadata:
  name: class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-deployment
  namespace: class
  labels:
    app: class-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class-deployment
  template:
    metadata:
      labels:
        app: class-deployment
    spec:
      containers:
      - name: httpd
        image: httpd:alpine3.20
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: class-svc
  namespace: class
spec:
  selector:
    app.kubernetes.io/name: class-deployment
  ports:
    - protocol: TCP
      port: 443
      name: port443
      targetPort: 443
    - protocol: TCP
      port: 80
      name: port80
      targetPort: 80
  type: LoadBalancer
