apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: class
  name: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: class
    spec:
      containers:
        - image: httpd:alpine3.20
          name: httpd
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: class
  name: class-svc
spec:
  type: LoadBalancer
  ports:
    - name: insecure
      port: 80
      protocol: TCP
      targetPort: 80
    - name: secure
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: class
status:
  loadBalancer: {}
