apiVersion: v1
kind: Service
metadata:
  name: class-svc
spec:
  type: NodePort    # Using NodePort to expose externally
  selector:
    app: class
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443