apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-11-29T14:27:35Z"
  generation: 2
  labels:
    app: apache-deployment
  name: apache-deployment
  namespace: qq3
  resourceVersion: "7007"
  uid: f74fc11c-5e31-410a-a05c-3c16c5026f18
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apache-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-deployment
    spec:
      containers:
        - image: httpd:bookworm
          imagePullPolicy: Always
          name: httpd
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-11-29T14:27:42Z"
      lastUpdateTime: "2024-11-29T14:27:42Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-11-29T14:27:35Z"
      lastUpdateTime: "2024-11-29T14:28:24Z"
      message: ReplicaSet "apache-deployment-dbb5654f7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
