apiVersion: v1
kind: Pod
metadata:
  name: limit
  namespace: qq3
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

